CREATE DATABASE IF NOT EXISTS coupons_db;

CREATE table coupons_db.COMPANIES ( ID INT(6) AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(30) NOT NULL);

CREATE table coupons_db.CUSTOMERS ( ID INT(6) AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(30) NOT NULL,
LAST_NAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(30) NOT NULL);

CREATE table coupons_db.CATEGORIES ( ID INT(6) AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30) NOT NULL);


CREATE table coupons_db.COUPONS ( ID INT(6) AUTO_INCREMENT PRIMARY KEY,
COMPANY_ID INT(6),
CATEGORY_ID INT(6),
TITLE VARCHAR(30) NOT NULL,
DESCRIPTION VARCHAR(30) NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
AMOUNT INT(6),
PRICE DOUBLE,
IMAGE VARCHAR(30) NOT NULL,
FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID),
FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID));

CREATE table coupons_db.CUSTOMERS_VS_COUPONS ( CUSTOMER_ID INT(6),
COUPON_ID INT(6),
PRIMARY KEY(CUSTOMER_ID,COUPON_ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
FOREIGN KEY (COUPON_ID) REFERENCES COUPONS(ID));